language: generic
sudo: required
dist: trusty

env:
    global:
        - LOCAL_SWIFT_BRANCH="swift-4.2-release"
        - LOCAL_SWIFT_VERSION="swift-4.2-RELEASE"
    matrix:
        # Swift 4.1
        - CURL="7.59.0" HTTP2="v1.31.0" SWIFT_BRANCH="swift-4.1-release" SWIFT_VERSION="swift-4.1-RELEASE" TAG="aleksaubry/swift-apns:4.1"
        # Swift 4.2
        - CURL="7.61.1" HTTP2="v1.33.0" SWIFT_BRANCH="swift-4.2-release" SWIFT_VERSION="swift-4.2-RELEASE" TAG="aleksaubry/swift-apns:4.2"
        # Swift 4.2.1
        - CURL="7.64.0" HTTP2="v1.36.0" SWIFT_BRANCH="swift-4.2.1-release" SWIFT_VERSION="swift-4.2.1-RELEASE" TAG="aleksaubry/swift-apns:4.2.1"
        # Swift 4.2.2
        - CURL="7.64.0" HTTP2="v1.36.0" SWIFT_BRANCH="swift-4.2.2-release" SWIFT_VERSION="swift-4.2.2-RELEASE" TAG="aleksaubry/swift-apns:4.2.2"
        # Swift 4.2.3
        - CURL="7.64.0" HTTP2="v1.36.0" SWIFT_BRANCH="swift-4.2.3-release" SWIFT_VERSION="swift-4.2.3-RELEASE" TAG="aleksaubry/swift-apns:4.2.3"
        # Swift 5.0 (03/06)
        - CURL="7.64.0" HTTP2="v1.36.0" SWIFT_BRANCH="swift-5.0-branch" SWIFT_VERSION="swift-5.0-DEVELOPMENT-SNAPSHOT-2019-03-06-a" TAG="aleksaubry/swift-apns:5.0-beta.306"

install:
    - bash ./.ci/install.sh

script:
    - bash ./.ci/build.sh

deploy:
    provider: script
    script: bash ./.ci/release.sh
    skip_cleanup: true
    on:
        tags: true
